import { useEffect, useMemo, useState } from 'react'
import type { DestinationBatchJob, DestinationBatchJobReviewReadModel } from '@shared/factory-batch-contracts'
import type { DestinationBatchRedoScope } from '@shared/factory-batch-contracts'
import { defaultRedoGuidance, type RedoGenerationGuidance } from '@shared/redo-guidance-contracts'
import { BATCH_LIVE_REFRESH_INTERVAL_MS, isActiveBatchJob, jobStatusLabel } from './factory-presentation'

type Tab = 'summary' | 'student' | 'adventure' | 'visuals' | 'traceability'

export function BatchReviewDesk({ jobId, onBack, onRedoAccepted }: { jobId: string; onBack: () => void; onRedoAccepted: (job: DestinationBatchJob, scope: DestinationBatchRedoScope) => void }): JSX.Element {
  const [review, setReview] = useState<DestinationBatchJobReviewReadModel | null>(null)
  const [tab, setTab] = useState<Tab>('summary')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [redoScope, setRedoScope] = useState<DestinationBatchRedoScope | null>(null)
  const [redoGuidance, setRedoGuidance] = useState<RedoGenerationGuidance | null>(null)
  const [redoReason, setRedoReason] = useState('')
  const load = async () => { setBusy(true); setError(null); try { setReview(await window.electronAPI.readDestinationBatchJobReview(jobId)) } catch (reason) { setError(errorText(reason)) } finally { setBusy(false) } }
  // The request is intentionally keyed solely by the durable job identity.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [jobId])
  const reviewIsActive = review ? isActiveBatchJob(review) : false
  const redoActive = Boolean(review?.redo && reviewIsActive)
  useEffect(() => {
    if (!reviewIsActive) return
    const timer = window.setInterval(() => { void window.electronAPI.readDestinationBatchJobReview(jobId).then(setReview).catch(() => undefined) }, BATCH_LIVE_REFRESH_INTERVAL_MS)
    return () => window.clearInterval(timer)
  }, [jobId, reviewIsActive])
  const approvalBlockers = review ? packageBlockingReasons(review) : ['PACKAGE_SNAPSHOT_REQUIRED']
  const canApprove = Boolean(review?.status === 'READY_FOR_REVIEW' && approvalBlockers.length === 0)
  const approve = async () => { if (!review?.structuredPackage || !review.structuredPackageArtifactId) return; setBusy(true); setError(null); try { await window.electronAPI.approveDestinationBatchJob({ jobId, structuredPackageArtifactId: review.structuredPackageArtifactId, packageId: review.structuredPackage.packageId }); await load() } catch (reason) { setError(errorText(reason)) } finally { setBusy(false) } }
  const chooseRedoScope = (scope: DestinationBatchRedoScope) => { setRedoScope(scope); setRedoGuidance(defaultRedoGuidance(scope)) }
  const requestRedo = async () => { if (!redoScope || !redoGuidance) return; setBusy(true); setError(null); try { const job = await window.electronAPI.requestDestinationBatchRedo({ jobId, scope: redoScope, guidance: redoGuidance, ...(redoReason.trim() ? { reason: redoReason.trim() } : {}) }); onRedoAccepted(job, redoScope) } catch (reason) { setError(errorText(reason)) } finally { setBusy(false) } }
  const adventureVisuals = useMemo(() => selectedVisuals(review, 'adventure'), [review])
  return <section className="review-desk" aria-label="Mesa de revisión humana">
    <button className="back-link" onClick={onBack}>← Volver al lote</button>
    {error && <div className="alert error"><strong>No se pudo solicitar el rehacer.</strong><span>{error}</span></div>}
    {!review ? <div className="empty-card"><span className="spinner" /><p>{busy ? 'Cargando revisión durable…' : 'No hay datos de revisión.'}</p></div> : <>
      <header className="review-desk-header"><div><span className="card-kicker">REVISIÓN EDITORIAL</span><h2>{review.destination.name}</h2><p>{review.destination.country}{review.destination.region ? ` · ${review.destination.region}` : ''} · Job {review.jobId}</p></div><div><span className={`state-badge state-${review.status.toLowerCase()}`}>{label(review.status)}</span><strong>{formatMoney(review.cost)}</strong></div></header>
      {redoActive && <div className="live-job-status" role="status"><span className="spinner" /><div><strong>{jobStatusLabel(review.status, review.redo?.scope)}</strong><small>Investighost está trabajando.</small></div></div>}
      <div className="review-tabs" role="tablist">{([['summary', 'Resumen'], ['student', 'Student'], ['adventure', 'Adventure'], ['visuals', 'Visuales'], ['traceability', 'Trazabilidad']] as const).map(([key, text]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{text}</button>)}</div>
      {tab === 'summary' && <section className="review-grid"><Metric label="Estado" value={label(review.status)} /><Metric label="Auto-review" value={reviewOutcomeLabel(review.reviewSummary?.outcome)} /><Metric label="Intentos" value={String(review.attempts)} /><Metric label="Visuales" value={visualPackageLabel(review.visualPackage?.state)} /><Metric label="Package estructurado" value={review.structuredPackage ? review.structuredPackage.state : 'Pendiente'} /><Metric label="Media ingress" value={mediaIngressLabel(review.mediaIngressState)} /><Metric label="Media subida" value={`${review.mediaUploadedCount}/${review.mediaAssetCount}`} /><Metric label="Media reutilizada" value={String(review.mediaReusedCount)} /><Metric label="Media fallida" value={String(review.mediaFailedCount)} />
        {review.structuredPackage && <><Metric label="Student estructurado" value={`${review.structuredPackage.student.document.blocks.length} bloques`} /><Metric label="Adventure estructurado" value={review.structuredPackage.adventure.document.copy.headline} /><Metric label="Hero" value={assetIntentLabel(review.structuredPackage.adventure.document.hero.asset)} /><Metric label="Visual Story" value={`${review.structuredPackage.adventure.document.visualStory.items.length} items`} /><Metric label="Places" value={placeSummary(review.structuredPackage)} /><Metric label="Visuales sin resolver" value={String(unresolvedVisualIntentCount(review.structuredPackage))} /><Metric label="Captions" value={captionSummary(review.structuredPackage)} /></>}
        {review.warnings.length > 0 && <div className="alert warning"><strong>Warnings</strong><span>{review.warnings.join(' · ')}</span></div>}
        {review.mediaBlockingIssues.length > 0 && <div className="alert warning"><strong>Media ingress</strong><span>{review.mediaBlockingIssues.join(' · ')} · Handoff bloqueado hasta MEDIA_COMPLETE.</span></div>}
        {review.lastError && <div className="alert error"><strong>Último error</strong><span>{review.lastError}</span></div>}
        <div className="review-actions"><div><strong>Aprobación humana</strong><small>Aprueba exactamente el snapshot estructurado mediante Library. No crea delivery.</small></div><button className="button secondary" disabled={review.status !== 'READY_FOR_REVIEW' || busy || redoActive} onClick={() => chooseRedoScope(redoScope ?? 'STUDENT')}>Rehacer</button><button className="button success" disabled={!canApprove || busy || Boolean(redoScope) || redoActive} title={canApprove ? 'Aprobar package' : approvalBlockers.join(' · ')} onClick={() => { void approve() }}>Aprobar package</button></div>
        {redoScope && redoGuidance && <section className="form-card guided-redo" aria-label="Confirmar rehacer guiado"><header><span className="card-kicker">NUEVA GENERACIÓN GUIADA</span><h3>Rehacer {redoLabel(redoScope)}</h3><p>Se conservarán: {preserved(redoScope)}. Se volverá a crear: {regenerated(redoScope)} y la revisión automática.</p></header><div className="guided-redo-scopes" role="tablist">{(['STUDENT', 'ADVENTURE', 'VISUALS', 'EDITORIAL'] as const).map(scope => <button key={scope} className={redoScope === scope ? 'active' : ''} onClick={() => chooseRedoScope(scope)}>{redoLabel(scope)}</button>)}</div><GuidedRedoControls guidance={redoGuidance} onChange={setRedoGuidance} /><label className="field"><span>Comentario opcional</span><input value={redoReason} maxLength={1000} onChange={event => setRedoReason(event.target.value)} placeholder="Qué debe mejorar" /></label><section className="guided-redo-summary"><strong>Resumen</strong><GuidanceSummary guidance={redoGuidance} />{redoReason.trim() && <p>Comentario: {redoReason.trim()}</p>}</section><footer className="guided-redo-actions"><button className="button ghost" disabled={busy} onClick={() => { setRedoScope(null); setRedoGuidance(null) }}>Cancelar</button><button className="button secondary" disabled={busy} onClick={() => { void requestRedo() }}>Rehacer {redoLabel(redoScope)}</button></footer></section>}
      </section>}
      {tab === 'student' && <><StructuredStudentSummary value={review.structuredPackage} /><DocumentReview title="Student · explicación editorial" document={review.student} /></>}
      {tab === 'adventure' && <section className="adventure-review"><StructuredAdventureSummary value={review.structuredPackage} /><div className="section-heading"><div><span className="card-kicker">VISUAL-FIRST</span><h3>{review.adventure?.title ?? 'Adventure pendiente'}</h3><p>Hero, highlights y galería abren la experiencia; el copy acompaña la selección.</p></div></div><VisualStrip title="Hero" items={adventureVisuals.hero} /><VisualStrip title="Highlights" items={adventureVisuals.highlight} /><VisualStrip title="Galería" items={adventureVisuals.gallery} /><DocumentReview title="Copy de Adventure" document={review.adventure} /></section>}
      {tab === 'visuals' && <section className="visual-review"><div className="section-heading"><div><span className="card-kicker">PAQUETE VISUAL</span><h3>{review.visualPackage?.state ?? 'Sin paquete'}</h3><p>Proveedor, origen y derechos se muestran por asset; la UI no depende de Wikimedia.</p></div></div><VisualResolutionSummary value={review.structuredPackage} /><VisualStrip title="Hero" items={selectedVisuals(review, 'adventure').hero} /><VisualStrip title="Highlights" items={selectedVisuals(review, 'adventure').highlight} /><VisualStrip title="Galería" items={selectedVisuals(review, 'adventure').gallery} /></section>}
      {tab === 'traceability' && <section className="traceability-card"><dl><div><dt>Lote</dt><dd>{review.batchId}</dd></div><div><dt>Job</dt><dd>{review.jobId}</dd></div><div><dt>Student revision</dt><dd>{review.student?.revisionId ?? '—'}</dd></div><div><dt>Adventure revision</dt><dd>{review.adventure?.revisionId ?? '—'}</dd></div><div><dt>Visual package</dt><dd>{review.visualPackageId ?? '—'}</dd></div><div><dt>Structured package</dt><dd>{review.structuredPackage?.packageId ?? '—'}</dd></div><div><dt>Review artifact</dt><dd>{review.reviewArtifactId ?? '—'}</dd></div>{review.redo && <><div><dt>Último rehacer</dt><dd>{redoLabel(review.redo.scope)} · {review.redo.status}</dd></div><div><dt>Controles</dt><dd>{review.redo.guidance ? <GuidanceSummary guidance={review.redo.guidance} /> : 'Generación heredada sin controles'}</dd></div><div><dt>Comentario</dt><dd>{review.redo.reason ?? 'No indicado'}</dd></div><div><dt>Revisión anterior</dt><dd>{previousReference(review.redo.previousArtifactRefs, review.redo.scope)}</dd></div></>}</dl></section>}
    </>}
  </section>
}

function DocumentReview({ title, document }: { title: string; document: DestinationBatchJobReviewReadModel['student'] }) { return <section className="document-review"><header><span className="card-kicker">LIBRARY CANDIDATE</span><h3>{title}</h3></header>{document ? <><h4>{document.title}</h4><article>{document.content}</article><small>Entry {document.libraryEntryId} · v {document.versionId} · r {document.revisionId}</small></> : <p>El perfil todavía no está disponible.</p>}</section> }
type StructuredPackage = NonNullable<DestinationBatchJobReviewReadModel['structuredPackage']>
function StructuredStudentSummary({ value }: { value: StructuredPackage | null }) { return value ? <section className="document-review"><header><span className="card-kicker">STUDENT DOCUMENT V1</span><h3>{value.student.document.headline}</h3></header><p>{value.student.document.lead.join(' ') || 'Sin entradilla.'}</p><small>{value.student.document.blocks.length} bloques · revisión {value.student.libraryRevision.revisionId}</small></section> : null }
function StructuredAdventureSummary({ value }: { value: StructuredPackage | null }) { return value ? <section className="document-review"><header><span className="card-kicker">ADVENTURE PACKAGE V1</span><h3>{value.adventure.document.copy.headline}</h3></header><p>{value.adventure.document.copy.hook}</p><small>Hero {assetIntentLabel(value.adventure.document.hero.asset)} · {value.adventure.document.visualStory.items.length} visual story · {placeSummary(value)}</small></section> : null }
function VisualResolutionSummary({ value }: { value: StructuredPackage | null }) { if (!value?.visualResolution) return <p className="muted">Resolución estructurada pendiente.</p>; const resolution = value.visualResolution; return <section className="document-review"><header><span className="card-kicker">RESOLUCIÓN ESTRUCTURADA</span><h3>{resolution.state}</h3></header><p>{resolution.resolved.length} asset(s) resueltos con derechos públicos y copy contextual.</p>{resolution.unresolved.length > 0 && <small>Warnings: {resolution.unresolved.map(item => `${item.intentId}: ${item.reason}`).join(' · ')}</small>}</section> }
function assetIntentLabel(asset: StructuredPackage['adventure']['document']['hero']['asset']) { return asset.status === 'INTENT' ? 'Pendiente' : 'Resuelto' }
function mediaIngressLabel(value: DestinationBatchJobReviewReadModel['mediaIngressState']) { return value === 'MEDIA_COMPLETE' ? 'Complete' : value === 'MEDIA_PARTIAL' ? 'Partial' : value === 'MEDIA_PENDING' ? 'Pending' : 'Sin ejecución' }
function placeSummary(value: StructuredPackage) { const categories = [...new Set(value.adventure.document.placesToGo.items.map(place => place.category))]; return categories.length ? `${categories.join(', ')} · ${value.adventure.document.placesToGo.items.length}` : 'Sin places' }
function unresolvedVisualIntentCount(value: StructuredPackage) { return value.visualIntents.filter(intent => {
  const student = value.student.document.blocks.some(block => block.type === 'figure' && block.resolution === 'INTENT' && block.visualIntentId === intent.id)
  const hero = value.adventure.document.hero.asset.status === 'INTENT' && value.adventure.document.hero.asset.visualIntentId === intent.id
  const story = value.adventure.document.visualStory.items.some(item => item.asset.status === 'INTENT' && item.asset.visualIntentId === intent.id)
  const place = value.adventure.document.placesToGo.items.some(item => item.asset?.status === 'INTENT' && item.asset.visualIntentId === intent.id)
  return student || hero || story || place
}).length }
function Metric({ label, value }: { label: string; value: string }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article> }
function VisualStrip({ title, items }: { title: string; items: VisualItem[] }) { return <section className="visual-strip"><h4>{title}</h4>{items.length === 0 ? <p className="muted">No hay selección para este rol.</p> : <div>{items.map(item => <article key={`${item.asset.assetId}:${item.selection.priority}`}><>{item.asset.sourceUrl && <img src={item.asset.sourceUrl} alt={item.asset.alt ?? item.asset.caption ?? ''} />}</><strong>{item.asset.caption ?? item.asset.alt ?? item.asset.associatedPlace ?? 'Imagen sin título'}</strong><small>Rol {item.selection.role} · {item.asset.category} · provider {item.asset.sourceName ?? 'unknown'} · {item.asset.rightsStatus}</small><small>Autor {item.asset.author ?? 'no indicado'} · {item.asset.license ?? 'licencia pendiente'}</small></article>)}</div>}</section> }
type VisualItem = { asset: NonNullable<DestinationBatchJobReviewReadModel['visualPackage']>['assets'][number]; selection: NonNullable<DestinationBatchJobReviewReadModel['visualPackage']>['selections'][number] }
function selectedVisuals(review: DestinationBatchJobReviewReadModel | null, mode: 'adventure' | 'student'): Record<'hero' | 'highlight' | 'gallery', VisualItem[]> { const result: Record<'hero' | 'highlight' | 'gallery', VisualItem[]> = { hero: [], highlight: [], gallery: [] }; if (!review?.visualPackage) return result; const assets = new Map(review.visualPackage.assets.map(asset => [asset.assetId, asset])); for (const selection of review.visualPackage.selections.filter(item => item.mode === mode)) { const asset = assets.get(selection.assetId); if (asset) result[selection.role].push({ asset, selection }) } return result }
function label(status: string) { return ({ QUEUED: 'En cola', PROCESSING: 'Procesando', READY_FOR_REVIEW: 'Lista para revisión', APPROVED: 'Aprobado', REDO_REQUIRED: 'Rehacer', DELIVERED: 'Entregado', FAILED: 'Fallido', BLOCKED_AMBIGUOUS: 'Ambiguo', REUSED: 'Reutilizable' } as Record<string, string>)[status] ?? status }
function reviewOutcomeLabel(outcome: unknown) { return ({ passed: 'Superada', passed_with_warnings: 'Superada con advertencias', failed: 'No superada' } as Record<string, string>)[typeof outcome === 'string' ? outcome : ''] ?? 'Pendiente' }
function visualPackageLabel(state: string | undefined) { return ({ PARTIAL: 'Parcial', APPROVED: 'Completo', DRAFT: 'Borrador' } as Record<string, string>)[state ?? ''] ?? 'Sin paquete' }
function captionSummary(value: StructuredPackage) { const resolution = value.visualResolution; return resolution ? `${resolution.resolved.filter(item => Boolean(item.caption)).length}/${resolution.resolved.length}` : 'Pendientes' }
function packageBlockingReasons(review: DestinationBatchJobReviewReadModel): string[] { const value = review.structuredPackage; const blocking: string[] = []; if (!value || !review.structuredPackageArtifactId) blocking.push('PACKAGE_SNAPSHOT_REQUIRED'); if (!review.student || !review.adventure || !review.visualPackageId || !review.reviewArtifactId) blocking.push('PACKAGE_COMPONENT_REQUIRED'); if (value?.state !== 'PACKAGE_READY_FOR_REVIEW') blocking.push('PACKAGE_NOT_READY_FOR_REVIEW'); if (value?.adventure.document.hero.asset.status !== 'RESOLVED') blocking.push('MANDATORY_HERO_UNRESOLVED'); if (value && unresolvedVisualIntentCount(value) > 0) blocking.push('UNRESOLVED_VISUALS'); if (!['passed', 'passed_with_warnings'].includes(String(review.reviewSummary?.outcome ?? ''))) blocking.push('AUTO_REVIEW_REQUIRED'); return blocking }
function formatMoney(value: number) { return new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(value) }
function errorText(reason: unknown) { return reason instanceof Error ? reason.message : String(reason) }
function redoLabel(scope: DestinationBatchRedoScope) { return ({ STUDENT: 'Student', ADVENTURE: 'Adventure', VISUALS: 'Imágenes', EDITORIAL: 'Contenido editorial' } as Record<DestinationBatchRedoScope, string>)[scope] }
function preserved(scope: DestinationBatchRedoScope) { return ({ STUDENT: 'investigación, análisis, Adventure e imágenes', ADVENTURE: 'investigación, análisis, Student e imágenes', VISUALS: 'investigación, análisis, Student y Adventure', EDITORIAL: 'investigación, análisis e imágenes' } as Record<DestinationBatchRedoScope, string>)[scope] }
function regenerated(scope: DestinationBatchRedoScope) { return ({ STUDENT: 'Student', ADVENTURE: 'Adventure', VISUALS: 'Imágenes', EDITORIAL: 'Student y Adventure' } as Record<DestinationBatchRedoScope, string>)[scope] }

function GuidedRedoControls({ guidance, onChange }: { guidance: RedoGenerationGuidance; onChange: (value: RedoGenerationGuidance) => void }) {
  const update = (key: string, value: string) => onChange({ ...guidance, controls: { ...guidance.controls, [key]: value } } as RedoGenerationGuidance)
  return <div className="guided-redo-control-sections">{guidanceSections(guidance.scope).map(section => <section className="guided-redo-control-section" key={section.title}><h4>{section.title}</h4><div className="guided-redo-controls">{section.controls.map(control => <fieldset key={control.key}><legend>{control.label}</legend><div className="review-tabs">{control.options.map(([value, text]) => <button key={value} type="button" className={(guidance.controls as Record<string, string>)[control.key] === value ? 'active' : ''} onClick={() => update(control.key, value)}>{text}</button>)}</div></fieldset>)}</div></section>)}</div>
}

type GuidedControl = { key: string; label: string; options: Array<[string, string]> }
type GuidedControlSection = { title: string; controls: GuidedControl[] }
const control = (key: string, label: string, options: Array<[string, string]>): GuidedControl => ({ key, label, options })
function guidanceSections(scope: DestinationBatchRedoScope): GuidedControlSection[] {
  const variation = control('variationFromPrevious', 'Cambio respecto al anterior', [['LIGHT', 'Ligero'], ['CLEAR', 'Claro'], ['VERY_DIFFERENT', 'Muy distinto']])
  if (scope === 'STUDENT') return [
    { title: 'Enfoque', controls: [control('academicRigor', 'Rigor académico', [['STANDARD', 'Estándar'], ['HIGH', 'Alto'], ['MAXIMUM', 'Máximo']]), control('depth', 'Profundidad', [['CONCISE', 'Concisa'], ['BALANCED', 'Equilibrada'], ['DEEP', 'Profunda']]), control('clarity', 'Claridad', [['STANDARD', 'Normal'], ['CLEARER', 'Más clara'], ['VERY_CLEAR', 'Muy clara']])] },
    { title: 'Contenido', controls: [control('historicalCulturalContext', 'Contexto histórico-cultural', [['NORMAL', 'Normal'], ['MORE_CONTEXT', 'Más contexto'], ['DEEP_CONTEXT', 'Profundo']]), control('detail', 'Detalle', [['CONCISE', 'Conciso'], ['BALANCED', 'Equilibrado'], ['MORE_DETAILED', 'Más detallado']]), control('formality', 'Formalidad', [['ACCESSIBLE', 'Accesible'], ['FORMAL', 'Formal'], ['ACADEMIC', 'Académica']])] },
    { title: 'Cambio respecto al anterior', controls: [variation] },
  ]
  if (scope === 'ADVENTURE') return [
    { title: 'Dirección editorial', controls: [control('quality', 'Calidad', [['STANDARD', 'Estándar'], ['HIGH', 'Alta'], ['MAXIMUM', 'Máxima']]), control('visualImpact', 'Impacto visual', [['NORMAL', 'Normal'], ['MORE_VISUAL', 'Más visual'], ['VERY_VISUAL', 'Muy visual']]), control('adventureIntensity', 'Aventura', [['NORMAL', 'Normal'], ['MORE_ADVENTUROUS', 'Más aventurero'], ['INTENSE', 'Intenso']]), control('originality', 'Originalidad', [['SIMILAR_APPROACH', 'Similar'], ['DIFFERENT', 'Diferente'], ['REINVENT_APPROACH', 'Reinventar']]), control('detail', 'Detalle', [['CONCISE', 'Conciso'], ['BALANCED', 'Equilibrado'], ['MORE_DESCRIPTIVE', 'Más descriptivo']])] },
    { title: 'Cambio respecto al anterior', controls: [variation] },
  ]
  if (scope === 'VISUALS') return [
    { title: 'Selección visual', controls: [control('impact', 'Impacto', [['BALANCED', 'Equilibrado'], ['MORE_SPECTACULAR', 'Más espectacular'], ['HIGH_IMPACT', 'Alto impacto']]), control('representativeness', 'Representatividad', [['BALANCED', 'Equilibrada'], ['MORE_REPRESENTATIVE', 'Más representativa']]), control('variety', 'Variedad', [['NORMAL', 'Normal'], ['MORE_VARIED', 'Más variada'], ['VERY_VARIED', 'Muy variada']]), control('landscape', 'Paisaje', [['NORMAL', 'Normal'], ['PRIORITIZE', 'Priorizar']]), control('heritage', 'Patrimonio', [['NORMAL', 'Normal'], ['PRIORITIZE', 'Priorizar']]), control('localLife', 'Vida local', [['NORMAL', 'Normal'], ['PRIORITIZE', 'Priorizar']]), control('avoidPreviousSimilarity', 'Evitar imágenes similares', [['OFF', 'No'], ['ON', 'Sí'], ['STRONG', 'Prioridad alta']])] },
  ]
  return [
    { title: 'Dirección editorial', controls: [control('quality', 'Calidad', [['STANDARD', 'Estándar'], ['HIGH', 'Alta'], ['MAXIMUM', 'Máxima']]), control('depth', 'Profundidad', [['BALANCED', 'Equilibrada'], ['DEEPER', 'Mayor']]), control('originality', 'Originalidad', [['NORMAL', 'Normal'], ['DIFFERENT', 'Diferente'], ['REINVENT_APPROACH', 'Reinventar']]), control('studentAcademicWeight', 'Peso académico de Student', [['NORMAL', 'Normal'], ['HIGHER', 'Mayor']]), control('adventureEmotionalWeight', 'Peso emocional de Adventure', [['NORMAL', 'Normal'], ['HIGHER', 'Mayor']]), control('detail', 'Detalle', [['CONCISE', 'Conciso'], ['BALANCED', 'Equilibrado'], ['MORE_DETAILED', 'Más detallado']])] },
    { title: 'Cambio respecto al anterior', controls: [variation] },
  ]
}

function GuidanceSummary({ guidance }: { guidance: RedoGenerationGuidance }) { return <p className="guided-redo-summary-lines">{Object.entries(guidance.controls).map(([key, value]) => `${humanControlLabel(key)}: ${humanValue(String(value))}`).join(' · ')}</p> }
function humanControlLabel(key: string) { return ({ quality: 'Calidad', visualImpact: 'Impacto visual', adventureIntensity: 'Aventura', originality: 'Originalidad', detail: 'Detalle', variationFromPrevious: 'Variación', academicRigor: 'Rigor académico', depth: 'Profundidad', clarity: 'Claridad', historicalCulturalContext: 'Contexto histórico-cultural', formality: 'Formalidad', impact: 'Impacto', representativeness: 'Representatividad', variety: 'Variedad', landscape: 'Paisaje', heritage: 'Patrimonio', localLife: 'Vida local', avoidPreviousSimilarity: 'Evitar similitud', studentAcademicWeight: 'Peso académico Student', adventureEmotionalWeight: 'Peso emocional Adventure' } as Record<string, string>)[key] ?? key }
function humanValue(value: string) { return ({ STANDARD: 'Estándar', HIGH: 'Alta', MAXIMUM: 'Máxima', NORMAL: 'Normal', MORE_VISUAL: 'Más visual', VERY_VISUAL: 'Muy visual', MORE_ADVENTUROUS: 'Más aventurero', INTENSE: 'Intenso', SIMILAR_APPROACH: 'Similar', DIFFERENT: 'Diferente', REINVENT_APPROACH: 'Reinventar', CONCISE: 'Conciso', BALANCED: 'Equilibrado', MORE_DESCRIPTIVE: 'Más descriptivo', LIGHT: 'Ligera', CLEAR: 'Clara', VERY_DIFFERENT: 'Muy distinta', DEEP: 'Profunda', CLEARER: 'Más clara', VERY_CLEAR: 'Muy clara', MORE_CONTEXT: 'Más contexto', DEEP_CONTEXT: 'Profundo', MORE_DETAILED: 'Más detallado', ACCESSIBLE: 'Accesible', FORMAL: 'Formal', ACADEMIC: 'Académica', MORE_SPECTACULAR: 'Más espectacular', HIGH_IMPACT: 'Alto impacto', MORE_REPRESENTATIVE: 'Más representativa', MORE_VARIED: 'Más variada', PRIORITIZE: 'Priorizar', OFF: 'No', ON: 'Sí', STRONG: 'Prioridad alta', DEEPER: 'Mayor', HIGHER: 'Mayor' } as Record<string, string>)[value] ?? value }
function previousReference(refs: Record<string, string>, scope: DestinationBatchRedoScope) { return scope === 'VISUALS' ? refs.VISUALS ?? 'No disponible' : scope === 'STUDENT' ? refs.STUDENT ?? 'No disponible' : scope === 'ADVENTURE' ? refs.ADVENTURE ?? 'No disponible' : `${refs.STUDENT ?? '—'} · ${refs.ADVENTURE ?? '—'}` }
