import { useEffect, useState } from 'react'
import type { DestinationBatchReadModel, DestinationBatchJob } from '@shared/factory-batch-contracts'
import { formatCost, jobPhaseLabel, jobStatusLabel } from './factory-presentation'

export function BatchDetail({ batchId, onBack, onOpenJob }: { batchId: string; onBack: () => void; onOpenJob: (job: DestinationBatchJob) => void }) {
  const [model, setModel] = useState<DestinationBatchReadModel | null>(null)
  useEffect(() => { void window.electronAPI.readDestinationBatch(batchId).then(setModel) }, [batchId])
  if (!model) return <section className="empty-card"><span className="spinner" /><p>Cargando lote durable…</p></section>
  const c = model.countsByStatus
  return <section className="batch-import-layout"><button className="back-link" onClick={onBack}>← Volver a producción</button><div className="section-heading"><div><span className="card-kicker">DETALLE DE LOTE</span><h2>{model.batch.name}</h2><p>{new Date(model.batch.createdAt).toLocaleString('es-ES')} · {jobStatusLabel(model.batch.status)}</p></div></div><div className="metric-grid compact"><Metric label="Total" value={model.batch.totalItems} /><Metric label="En cola" value={c.QUEUED ?? 0} /><Metric label="Procesando" value={c.PROCESSING ?? 0} /><Metric label="Para revisar" value={c.READY_FOR_REVIEW ?? 0} /><Metric label="Aprobados" value={c.APPROVED ?? 0} /><Metric label="Rehacer" value={c.REDO_REQUIRED ?? 0} /><Metric label="Fallidos" value={c.FAILED ?? 0} /><Metric label="Coste" value={formatCost(model.jobs.reduce((n, job) => n + job.actualCost, 0))} /></div><section className="research-table">{model.jobs.map(job => <button className="research-row" key={job.id} onClick={() => onOpenJob(job)}><div className="destination-avatar">{job.originalName.slice(0,2)}</div><div className="research-main"><strong>{job.originalName}</strong><small>{job.country}{job.region ? ` · ${job.region}` : ''}</small></div><div className="stage-copy"><strong>{jobPhaseLabel(job.currentPhase)}</strong><small>{job.attemptCount} intentos · {formatCost(job.actualCost)}</small></div><span className={`state-badge state-${job.status.toLowerCase()}`}>{jobStatusLabel(job.status)}</span><span className="row-arrow">›</span></button>)}</section></section>
}
export function BatchJobDetail({ job, onBack, onOpenReview }: { job: DestinationBatchJob; onBack: () => void; onOpenReview: () => void }) { return <section className="batch-import-layout"><button className="back-link" onClick={onBack}>← Volver al lote</button><div className="section-heading"><div><h2>{job.originalName}</h2><p>{job.country}{job.region ? ` · ${job.region}` : ''}</p></div><span className={`state-badge state-${job.status.toLowerCase()}`}>{jobStatusLabel(job.status)}</span></div><div className="metric-grid compact"><Metric label="Fase" value={jobPhaseLabel(job.currentPhase)} /><Metric label="Coste" value={formatCost(job.actualCost)} /><Metric label="Intentos" value={job.attemptCount} /></div>{job.lastFailure && <div className="alert warning"><strong>Incidencia</strong><span>{job.lastFailure}</span></div>}{job.status === 'READY_FOR_REVIEW' && <button className="button primary" onClick={onOpenReview}>Abrir revisión</button>}</section> }
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article> }
